//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Observer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ObserverDBEntities : DbContext
    {
        public ObserverDBEntities()
            : base("name=ObserverDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<LabelsMap> LabelsMap { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<PhotoViolation> PhotoViolation { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Violations> Violations { get; set; }
    }
}
