//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Observer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Violations()
        {
            this.LabelsMap = new HashSet<LabelsMap>();
            this.Messages = new HashSet<Messages>();
            this.PhotoViolation = new HashSet<PhotoViolation>();
        }
    
        public int Id { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Like { get; set; }
        public Nullable<int> Dislaid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Type_violation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelsMap> LabelsMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messages> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoViolation> PhotoViolation { get; set; }
    }
}
